
theme: minima
title: Ernest Cheong
author: Ernest Cheong
email: afewcarbon@toms.com
description: > # this means to ignore newlines until "baseurl:"
  Adventures of an Ernest

# social links
twitter_username: doesnotexist # DO NOT include the @ character, or else the build will fail!
github_username:  ZeKaiCheong # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
